# За баланс хз, вроде достаточно дорогие
- type: latheRecipe
  id: LPPBorgModuleSecurityWeapon
  result: LPPBorgModuleSecurityWeapon
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 500

- type: latheRecipe
  id: LPPBorgModuleSecurityLaserCarbine
  result: LPPBorgModuleSecurityLaserCarbine
  materials:
    Steel: 3000
    Glass: 1000
    Plastic: 500

- type: latheRecipe
  id: LPPBorgModuleSecurityCriminologist
  result: LPPBorgModuleSecurityCriminologist
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 800

- type: latheRecipe
  id: LPPC4Low
  result: LPPC4Low
  completetime: 10
  materials:
    Plastic: 375
    Plasma: 375
